### ISSUE TITLE
Report portal service launch error

### ISSUE THREAD

**Issue by vinay-kabbe** [reportportal/agent-java-cucumber#103]
Report portal gives the exception 
2024-09-26 16:08:17,483 [main] INFO  c.epam.reportportal.service.Launch - Rerun: false
2024-09-26 16:08:18,346 [rp-io-1] ERROR c.epam.reportportal.service.Launch - [21] ReportPortal execution error
retrofit2.adapter.rxjava2.HttpException: HTTP 405 
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:57)
	at retrofit2.adapter.rxjava2.BodyObservable$BodyObserver.onNext(BodyObservable.java:38)
	at retrofit2.adapter.rxjava2.CallExecuteObservable.subscribeActual(CallExecuteObservable.java:48)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at retrofit2.adapter.rxjava2.BodyObservable.subscribeActual(BodyObservable.java:35)
	at io.reactivex.Observable.subscribe(Observable.java:12267)
	at io.reactivex.internal.operators.observable.ObservableSubscribeOn$SubscribeTask.run(ObservableSubscribeOn.java:96)
**Steps to Reproduce**
1. Set the cucumber options as below 
@Listeners(CucumberTestNGListener.class)
@CucumberOptions(
        features = {"src/test/resources/features/some_feature_name.feature"},
        glue = {"com.epam.stepdefinitions","com.epam.framework.runners.cucumber"},
        plugin =  {"pretty", "com.epam.reportportal.cucumber.StepReporter","com.epam.reportportal.cucumber.ScenarioReporter"}
)
**Expected behavior**
Report portal should generate the necessary output

**Actual behavior**
It is giving the exception as above

**Dependency versions**
Include version info of the following libraries: client-java, agent-java-cucumber
java version : openjdk version 18.0.1
testng version : 7.1.0
cucumber version : 7.18.0
report portal pom dependency used 
<dependency>
			<groupId>com.epam.reportportal</groupId>
			<artifactId>agent-java-cucumber6</artifactId>
			<version>5.1.0-RC-3</version>
		</dependency>

**Additional context**
used all the reportportal properties from the report portal user profile.

**Comment by vinay-kabbe** [comment]
this is a blocker for me , please help 

Please also let me know here , if you need any more info
