### ISSUE TITLE
Cannot load class from file: com.epam.reportportal.testng.ReportPortalListener

### ISSUE THREAD

**Issue by whaque81** [reportportal/agent-java-cucumber#24]
Using **ReportPortal 3.0.1, TestNG 6.14.3, Gherkin 5.1.0 and Cucumber 2.4.0**, gives me error:

```
org.testng.TestNGException: 
Cannot load class from file: com.epam.reportportal.testng.ReportPortalListener
	at org.testng.internal.ClassHelper.fileToClass(ClassHelper.java:551)
	at org.testng.TestNG.configure(TestNG.java:1440)
	at org.testng.TestNG.configure(TestNG.java:1619)
	at org.apache.maven.surefire.testng.conf.TestNGMapConfigurator.configure(TestNGMapConfigurator.java:56)
	at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:132)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.executeSingleClass(TestNGDirectoryTestSuite.java:112)
	at org.apache.maven.surefire.testng.TestNGDirectoryTestSuite.execute(TestNGDirectoryTestSuite.java:99)
	at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:146)
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:386)
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:323)
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:143)
```
What could be the root cause?

**Comment by DzmitryHumianiuk** [comment]
@whaque81 check your dependencies
https://github.com/reportportal/agent-java-testNG#dependencies
