### ISSUE TITLE
java.lang.NoSuchMethodError: io.cucumber.cucumberexpressions.Expression.match(Ljava/lang/String;)Ljava/util/List;

### ISSUE THREAD

**Issue by lgoldstein** [reportportal/agent-java-cucumber#26]
Occurs when trying to use Cucumber JVM 4.1.1 with _expressions_ 6.2.0
```
      java.lang.NoSuchMethodError: io.cucumber.cucumberexpressions.Expression.match(Ljava/lang/String;)Ljava/util/List;
	at io.cucumber.stepexpression.StepExpression.match(StepExpression.java:21)
	at io.cucumber.stepexpression.StepExpression.match(StepExpression.java:33)
	at io.cucumber.stepexpression.ExpressionArgumentMatcher.argumentsFrom(ExpressionArgumentMatcher.java:30)
	at cucumber.runtime.java.JavaStepDefinition.matchedArguments(JavaStepDefinition.java:53)
	at cucumber.runner.Glue.stepDefinitionMatches(Glue.java:104)
	at cucumber.runner.Glue.stepDefinitionMatch(Glue.java:82)
	at cucumber.runner.Runner.addTestStepsForPickleSteps(Runner.java:64)
	at cucumber.runner.Runner.createTestCaseForPickle(Runner.java:54)
	at cucumber.runner.Runner.runPickle(Runner.java:39)
	at cucumber.runtime.junit.PickleRunners$NoStepDescriptions.run(PickleRunners.java:146)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:68)
	at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:23)
```

**Comment by lgoldstein** [comment]
Upgrading to Cucumber 4.2.2 solves this issue
