### ISSUE TITLE
I get "Field 'launchId' should not contain only white spaces and shouldn't be empty" agent and RP version 5

### ISSUE THREAD

**Issue by evgenytkachenko** [reportportal/agent-java-cucumber#37]
ReportPortal Finish test item execution error
com.epam.reportportal.exception.ReportPortalException: Report Portal returned error
Status code: 400
Status message: Bad Request
Error Message: Incorrect Request. [Field 'launchId' should not contain only white spaces and shouldn't be empty.] 
Error Type: INCORRECT_REQUEST

	at com.epam.reportportal.service.ReportPortalErrorHandler.handleError(ReportPortalErrorHandler.java:83)
	at com.epam.reportportal.service.ReportPortalErrorHandler.handle(ReportPortalErrorHandler.java:59)
	at com.epam.reportportal.restendpoint.http.HttpClientRestEndpoint$1.subscribe(HttpClientRestEndpoint.java:517)
	at io.reactivex.internal.operators.maybe.MaybeCreate.subscribeActual(MaybeCreate.java:45)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeCache.subscribeActual(MaybeCache.java:77)
	at io.reactivex.Maybe.subscribe(Maybe.java:4290)
	at io.reactivex.internal.operators.maybe.MaybeSubscribeOn$SubscribeTask.run(MaybeSubscribeOn.java:54)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:38)
	at io.reactivex.internal.schedulers.ScheduledDirectTask.call(ScheduledDirectTask.java:26)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

project.ext {
    cucumberVersion = '1.2.5'
    junitVersion = '4.12'
}

dependencies {
    testCompile "info.cukes:cucumber-java:${cucumberVersion}"
    testCompile "info.cukes:cucumber-junit:${cucumberVersion}"

    testCompile 'ch.qos.logback:logback-classic:1.2.3'
    testCompile 'info.cukes:gherkin:2.12.2'

    testCompile "junit:junit:${junitVersion}"
    testCompile 'com.epam.reportportal:agent-java-cucumber:5.0.0-BETA-1'

}

**Comment by evgenytkachenko** [comment]
I had to use

com.epam.reportportal
agent-java-cucumber4
5.0.0-BETA-1
I used

com.epam.reportportal
agent-java-cucumber
5.0.0-BETA-1
