### ISSUE TITLE
cucumber.runtime.CucumberException: Only one formatter can use STDOUT, now both pretty and pretty use it. If you use more than one formatter you must specify output path with PLUGIN:PATH_OR_URL

### ISSUE THREAD

**Issue by Sivasankaramalan** [reportportal/agent-java-cucumber#62]
cucumber.runtime.CucumberException: Only one formatter can use STDOUT, now both pretty and pretty use it. If you use more than one formatter you must specify output path with PLUGIN:PATH_OR_URL
	at cucumber.runtime.formatter.PluginFactory.defaultOutOrFailIfAlreadyUsed(PluginFactory.java:185)
	at cucumber.runtime.formatter.PluginFactory.convertOrNull(PluginFactory.java:144)
	at cucumber.runtime.formatter.PluginFactory.instantiate(PluginFactory.java:99)
	at cucumber.runtime.formatter.PluginFactory.create(PluginFactory.java:87)
	at cucumber.runtime.RuntimeOptions.getPlugins(RuntimeOptions.java:245)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:291)
	at com.sun.proxy.$Proxy17.done(Unknown Source)
	at cucumber.runtime.junit.JUnitReporter.done(JUnitReporter.java:227)
	at cucumber.api.junit.Cucumber.run(Cucumber.java:101)
	at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
	at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:542)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:770)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:464)
	at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:210)

**Comment by Sivasankaramalan** [comment]
Hey, can you guys help me with this issue?  here is my runner file
`@RunWith(Cucumber.class)
@CucumberOptions(plugin = { "pretty", "com.epam.reportportal.cucumber.ScenarioReporter"},
				 
//{ "com.cucumber.listener.ExtentCucumberFormatter:" },
				 features = {"src/test/resources/features/CollectionFeatures.feature" },

//				 glue="Driver.stepDefs",

//				 tags= {"~@Sanity","@Regression"},
				
				 

		monochrome = true)

public class Runner { 

	@BeforeClass
	public static void setup() {
		Log.startLog("Test Starts from Here");
		String timeStamp = new SimpleDateFormat("yyyy.MM.dd.HH.mm.ss").format(new Date());
		ExtentProperties extentProperties = ExtentProperties.INSTANCE;
		extentProperties
				.setReportPath("target/cucumber-reports/" + timeStamp.replace(":", "_").replace(".", "_") + ".html");
	}

	@AfterClass
	public static void writeExtentReport() {

		Reporter.loadXMLConfig(new File(System.getProperty("user.dir") + "/target/extent-config.xml"));
		Reporter.setSystemInfo("User Name", System.getProperty("user.name"));
		Reporter.setSystemInfo("Time Zone", System.getProperty("user.timezone"));
		Log.endLog("Test Ends Here");
	}`

**Comment by HardNorth** [comment]
Just specify any string name for output after reporter class name as in the exception:
`@CucumberOptions(plugin = { "pretty", "com.epam.reportportal.cucumber.ScenarioReporter:output1"})`
