### ISSUE TITLE
StringIndexOutOfBoundsException when running a test

### ISSUE THREAD

**Issue by restagner** [reportportal/agent-java-cucumber#76]
I'm encountering the following stack trace when I attempt to execute a test

```java
Exception in thread "main" java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.lang.String.substring(String.java:1967)
	at com.epam.reportportal.cucumber.AbstractReporter.getCodeRef(AbstractReporter.java:714)
	at com.epam.reportportal.cucumber.AbstractReporter.buildStartStepRequest(AbstractReporter.java:312)
	at com.epam.reportportal.cucumber.ScenarioReporter.buildStartStepRequest(ScenarioReporter.java:66)
	at com.epam.reportportal.cucumber.AbstractReporter.beforeStep(AbstractReporter.java:335)
	at com.epam.reportportal.cucumber.ScenarioReporter.beforeStep(ScenarioReporter.java:73)
	at com.epam.reportportal.cucumber.AbstractReporter.match(AbstractReporter.java:473)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at cucumber.runtime.Utils$1.call(Utils.java:40)
	at cucumber.runtime.Timeout.timeout(Timeout.java:16)
	at cucumber.runtime.Utils.invoke(Utils.java:34)
	at cucumber.runtime.RuntimeOptions$1.invoke(RuntimeOptions.java:294)
	at com.sun.proxy.$Proxy13.match(Unknown Source)
	at cucumber.runtime.Runtime.runStep(Runtime.java:279)
	at cucumber.runtime.model.StepContainer.runStep(StepContainer.java:44)
	at cucumber.runtime.model.StepContainer.runSteps(StepContainer.java:39)
	at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:44)
	at cucumber.runtime.model.CucumberFeature.run(CucumberFeature.java:165)
	at cucumber.runtime.Runtime.run(Runtime.java:122)
	at cucumber.api.cli.Main.run(Main.java:36)
	at cucumber.api.cli.Main.main(Main.java:18)
```

The error refers to line 714 in the `AbstractReporter.getCodeRef` method, which looks like

```java
return fullCodeRef != null ? fullCodeRef.substring(0, fullCodeRef.indexOf(METHOD_OPENING_BRACKET)) : null;
```

My setup
- agent-java-cucumber (v5.1.0-RC-2)
- cucumber-groovy (v1.2.5)
- Java SDK (v1.8.0_181)

Any thoughts as to why this is happening?

**Comment by HardNorth** [comment]
@restagner It looks like I missed the case of cucumber + groovy integration. Can you provide any example project, which I could use as a test case?

**Comment by restagner** [comment]
@HardNorth, I can provide you with where in the groovy code it's breaking.  

Within my project (unfortunately, proprietary, so I can't share entire project), the exception occurs at the **Before** code block, which exists within the `env.groovy` script.

```groovy
Before() { ScenarioImpl scenario ->
    testEnvironment.setScenarioName(scenario.name)
    // load environment -- includes loading config and command line settings, along with initializing
    // a WebDriver object
    testEnvironment.loadTestEnvironment()
    .
    .
    .
}    
```

**NOTE**: there is also an **After** block within the `env.groovy` script that will likely encounter a similar issue.

Is this sufficient enough for you @HardNorth ?  If not, I can update a personal github repo (it's kinda outdated), that contains the basic foundation of groovy + cucumber. Let me know.

**Comment by restagner** [comment]
@HardNorth **UPDATE**: I _found_ a repository that should help you with testing.  Reference: https://github.com/restagner/cucumber-groovy-selenium

**Comment by HardNorth** [comment]
@restagner Thanks, let me check this out today.

**Comment by HardNorth** [comment]
Fixed in https://github.com/reportportal/agent-java-cucumber/releases/tag/5.1.0-RC-3

Should be available on Maven Central in 20 minutes.

**Comment by restagner** [comment]
@HardNorth , it appears to be working :-) (see below screen shots)

![ReportPortal Issue 74-1](https://user-images.githubusercontent.com/798521/130649960-59eabe36-ef11-4239-be29-8fa08102a936.png)
![ReportPortal Issue 74-2](https://user-images.githubusercontent.com/798521/130649970-add34f2b-16d3-48bd-854c-65d2f213e4d2.png)
