### ISSUE TITLE
No such method error CucumberException: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder

### ISSUE THREAD

**Issue by Phalguna2125** [reportportal/agent-java-cucumber#92]
Hi ,

I am trying to use ScenarioReporter plugin in multi.module gradle project with previously with cucumber-java8 and as we migrated to cucumber-java. I have faced issues with AbstractMethoderror

`
```
Receiver class com.epam.reportportal.cucumber.AbstractReporter$$Lambda$443/0x0000000100379c40 does not define or inherit an implementation of the resolved method abstract receive(Ljava/lang/Object;)V of interface io.cucumber.plugin.event.EventHandler.

java.lang.AbstractMethodError: Receiver class com.epam.reportportal.cucumber.AbstractReporter$$Lambda$443/0x0000000100379c40 does not define or inherit an implementation of the resolved method abstract receive(Ljava/lang/Object;)V of interface io.cucumber.plugin.event.EventHandler`

```
Followed by trying imported agent-java-cucumber6 . Post that i am facing NoSuchMethoderror

Specs i am using are
io.cucumber : cucumber-java 7.12.1
agent-java-cucumber6 5.2.0

Not sure is this related to Plugin. But as far as error i see its missing method from the ReportPortal. Am i missing any configuration??

Can you provide any suggestions or comments on this issue

```

Caused by: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;

       at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)

       at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)

       at java.base/java.util.Optional.orElseGet(Optional.java:369)

       at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)

       at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)

       at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:193)

       at com.epam.reportportal.cucumber.AbstractReporter.<init>(AbstractReporter.java:90)

       at com.epam.reportportal.cucumber.ScenarioReporter.<init>(ScenarioReporter.java:49)

       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

       at 
       at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Caused by: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;

       at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)

       at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)

       at java.base/java.util.Optional.orElseGet(Optional.java:369)

       at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)

       at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)

       at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:193)

       at com.epam.reportportal.cucumber.AbstractReporter.<init>(AbstractReporter.java:90)

       at com.epam.reportportal.cucumber.ScenarioReporter.<init>(ScenarioReporter.java:49)

       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

       at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)
`
```

**Comment by Phalguna2125** [comment]
I believe this ia due to improper version. Could you please point out what i am missing.

Thanks for the help in advance
