### ISSUE TITLE
java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout

### ISSUE THREAD

**Issue by Phalguna2125** [reportportal/agent-java-cucumber#93]
Is cucumber-java :7.12.1 supported by agent-java-cucumber6? I see in the docs its supported till 7.0.0 of cucumber-java and junit.
 
I am using agent-java-cucumber6:5.2.0 along with cucumber-java 7.12.1.
I am facing issue of following error. Could you let me know whats the issue

```org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)

       at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:113)

       at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:65)

       at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)

       at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)

Caused by: java.lang.NoSuchMethodError: okhttp3.OkHttpClient$Builder.callTimeout(Ljava/time/Duration;)Lokhttp3/OkHttpClient$Builder;

       at com.epam.reportportal.service.ReportPortal$Builder.defaultClient(ReportPortal.java:542)

       at com.epam.reportportal.service.ReportPortal$Builder.lambda$buildClient$1(ReportPortal.java:430)

       at java.base/java.util.Optional.orElseGet(Optional.java:369)

       at com.epam.reportportal.service.ReportPortal$Builder.buildClient(ReportPortal.java:430)

       at com.epam.reportportal.service.ReportPortal$Builder.build(ReportPortal.java:407)

       at com.epam.reportportal.cucumber.AbstractReporter.buildReportPortal(AbstractReporter.java:193)

       at com.epam.reportportal.cucumber.AbstractReporter.<init>(AbstractReporter.java:90)

       at com.epam.reportportal.cucumber.ScenarioReporter.<init>(ScenarioReporter.java:49)

       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)

       at io.cucumber.core.plugin.PluginFactory.newInstance(PluginFactory.java:116)

       ... 65 more
 ```

**Comment by HardNorth** [comment]
@Phalguna2125 I have to warn you not to spam us with duplicate issues, or you might get blocked in our community.
Duplicates: https://github.com/reportportal/agent-java-cucumber6/issues/38
